project:
  type: website
  output-dir: docs

website:
  title: "mb-data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        file: about.qmd
          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



