project:
  type: website
  output-dir: docs

website:
  title: "mb-data"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        file: about.qmd
      - text: "Tutorials"
        #file: tutorials.qmd
        menu:
          - text: Learn R
            href: /tutorial-LearnR
          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



